/*
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CreateStandaloneSetup extends CreateStandaloneSetupGenerated {

	def static void doSetup() {
		new CreateStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
