/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Combination</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.AddCombination#getAdd <em>Add</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getAddCombination()
 * @model
 * @generated
 */
public interface AddCombination extends CombinationRaiseType
{
  /**
   * Returns the value of the '<em><b>Add</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Add</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add</em>' containment reference.
   * @see #setAdd(Combination)
   * @see de.wilkenk.ba.create.CreatePackage#getAddCombination_Add()
   * @model containment="true"
   * @generated
   */
  Combination getAdd();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.AddCombination#getAdd <em>Add</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Add</em>' containment reference.
   * @see #getAdd()
   * @generated
   */
  void setAdd(Combination value);

} // AddCombination
