/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Raise</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.AttributeRaise#getTarget <em>Target</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.AttributeRaise#getTries <em>Tries</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.AttributeRaise#getValueChange <em>Value Change</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getAttributeRaise()
 * @model
 * @generated
 */
public interface AttributeRaise extends Raise
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(Attribute)
   * @see de.wilkenk.ba.create.CreatePackage#getAttributeRaise_Target()
   * @model
   * @generated
   */
  Attribute getTarget();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.AttributeRaise#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Attribute value);

  /**
   * Returns the value of the '<em><b>Tries</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tries</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tries</em>' attribute.
   * @see #setTries(int)
   * @see de.wilkenk.ba.create.CreatePackage#getAttributeRaise_Tries()
   * @model
   * @generated
   */
  int getTries();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.AttributeRaise#getTries <em>Tries</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tries</em>' attribute.
   * @see #getTries()
   * @generated
   */
  void setTries(int value);

  /**
   * Returns the value of the '<em><b>Value Change</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Change</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Change</em>' containment reference.
   * @see #setValueChange(AttributeRaiseType)
   * @see de.wilkenk.ba.create.CreatePackage#getAttributeRaise_ValueChange()
   * @model containment="true"
   * @generated
   */
  AttributeRaiseType getValueChange();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.AttributeRaise#getValueChange <em>Value Change</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Change</em>' containment reference.
   * @see #getValueChange()
   * @generated
   */
  void setValueChange(AttributeRaiseType value);

} // AttributeRaise
