/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Category</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.wilkenk.ba.create.CreatePackage#getCategory()
 * @model
 * @generated
 */
public interface Category extends Entity
{
} // Category
