/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Character</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.Character#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getCharacter()
 * @model
 * @generated
 */
public interface Character extends Entity
{
  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link de.wilkenk.ba.create.Property}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Properties</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see de.wilkenk.ba.create.CreatePackage#getCharacter_Properties()
   * @model containment="true"
   * @generated
   */
  EList<Property> getProperties();

} // Character
