/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Combined Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.CombinedAttribute#getMinValue <em>Min Value</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.CombinedAttribute#getMaxValue <em>Max Value</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.CombinedAttribute#getCombValue <em>Comb Value</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.CombinedAttribute#getCategory <em>Category</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.CombinedAttribute#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getCombinedAttribute()
 * @model
 * @generated
 */
public interface CombinedAttribute extends Entity
{
  /**
   * Returns the value of the '<em><b>Min Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Min Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Value</em>' attribute.
   * @see #setMinValue(int)
   * @see de.wilkenk.ba.create.CreatePackage#getCombinedAttribute_MinValue()
   * @model
   * @generated
   */
  int getMinValue();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.CombinedAttribute#getMinValue <em>Min Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Value</em>' attribute.
   * @see #getMinValue()
   * @generated
   */
  void setMinValue(int value);

  /**
   * Returns the value of the '<em><b>Max Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Max Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Value</em>' attribute.
   * @see #setMaxValue(int)
   * @see de.wilkenk.ba.create.CreatePackage#getCombinedAttribute_MaxValue()
   * @model
   * @generated
   */
  int getMaxValue();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.CombinedAttribute#getMaxValue <em>Max Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Value</em>' attribute.
   * @see #getMaxValue()
   * @generated
   */
  void setMaxValue(int value);

  /**
   * Returns the value of the '<em><b>Comb Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comb Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comb Value</em>' containment reference.
   * @see #setCombValue(MathExpression)
   * @see de.wilkenk.ba.create.CreatePackage#getCombinedAttribute_CombValue()
   * @model containment="true"
   * @generated
   */
  MathExpression getCombValue();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.CombinedAttribute#getCombValue <em>Comb Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comb Value</em>' containment reference.
   * @see #getCombValue()
   * @generated
   */
  void setCombValue(MathExpression value);

  /**
   * Returns the value of the '<em><b>Category</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Category</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Category</em>' reference.
   * @see #setCategory(Category)
   * @see de.wilkenk.ba.create.CreatePackage#getCombinedAttribute_Category()
   * @model
   * @generated
   */
  Category getCategory();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.CombinedAttribute#getCategory <em>Category</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Category</em>' reference.
   * @see #getCategory()
   * @generated
   */
  void setCategory(Category value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see de.wilkenk.ba.create.CreatePackage#getCombinedAttribute_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.CombinedAttribute#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

} // CombinedAttribute
