/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Combination Raise Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.wilkenk.ba.create.CreatePackage#getCombinationRaiseType()
 * @model
 * @generated
 */
public interface CombinationRaiseType extends EObject
{
} // CombinationRaiseType
