/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Combination Raise</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.CombinationRaise#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getCombinationRaise()
 * @model
 * @generated
 */
public interface CombinationRaise extends Raise
{
  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link de.wilkenk.ba.create.CombinationRaiseType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see de.wilkenk.ba.create.CreatePackage#getCombinationRaise_Actions()
   * @model containment="true"
   * @generated
   */
  EList<CombinationRaiseType> getActions();

} // CombinationRaise
