/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Combination Part</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see de.wilkenk.ba.create.CreatePackage#getCombinationPart()
 * @model
 * @generated
 */
public enum CombinationPart implements Enumerator
{
  /**
   * The '<em><b>Combination Name</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COMBINATION_NAME_VALUE
   * @generated
   * @ordered
   */
  COMBINATION_NAME(0, "combinationName", "combinationName"),

  /**
   * The '<em><b>Combination Conditions</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COMBINATION_CONDITIONS_VALUE
   * @generated
   * @ordered
   */
  COMBINATION_CONDITIONS(1, "combinationConditions", "combinationConditions");

  /**
   * The '<em><b>Combination Name</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Combination Name</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #COMBINATION_NAME
   * @model name="combinationName"
   * @generated
   * @ordered
   */
  public static final int COMBINATION_NAME_VALUE = 0;

  /**
   * The '<em><b>Combination Conditions</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Combination Conditions</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #COMBINATION_CONDITIONS
   * @model name="combinationConditions"
   * @generated
   * @ordered
   */
  public static final int COMBINATION_CONDITIONS_VALUE = 1;

  /**
   * An array of all the '<em><b>Combination Part</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final CombinationPart[] VALUES_ARRAY =
    new CombinationPart[]
    {
      COMBINATION_NAME,
      COMBINATION_CONDITIONS,
    };

  /**
   * A public read-only list of all the '<em><b>Combination Part</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<CombinationPart> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Combination Part</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static CombinationPart get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      CombinationPart result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Combination Part</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static CombinationPart getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      CombinationPart result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Combination Part</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static CombinationPart get(int value)
  {
    switch (value)
    {
      case COMBINATION_NAME_VALUE: return COMBINATION_NAME;
      case COMBINATION_CONDITIONS_VALUE: return COMBINATION_CONDITIONS;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private CombinationPart(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //CombinationPart
