/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.Condition#getCondName <em>Cond Name</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.Condition#getExpression <em>Expression</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.Condition#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
   * Returns the value of the '<em><b>Cond Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cond Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond Name</em>' attribute.
   * @see #setCondName(String)
   * @see de.wilkenk.ba.create.CreatePackage#getCondition_CondName()
   * @model
   * @generated
   */
  String getCondName();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.Condition#getCondName <em>Cond Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond Name</em>' attribute.
   * @see #getCondName()
   * @generated
   */
  void setCondName(String value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(ConditionTargets)
   * @see de.wilkenk.ba.create.CreatePackage#getCondition_Expression()
   * @model containment="true"
   * @generated
   */
  ConditionTargets getExpression();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.Condition#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(ConditionTargets value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see de.wilkenk.ba.create.CreatePackage#getCondition_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.Condition#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

} // Condition
