/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.wilkenk.ba.create.CreatePackage
 * @generated
 */
public interface CreateFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CreateFactory eINSTANCE = de.wilkenk.ba.create.impl.CreateFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Domainmodel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Domainmodel</em>'.
   * @generated
   */
  Domainmodel createDomainmodel();

  /**
   * Returns a new object of class '<em>Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity</em>'.
   * @generated
   */
  Entity createEntity();

  /**
   * Returns a new object of class '<em>Character</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Character</em>'.
   * @generated
   */
  Character createCharacter();

  /**
   * Returns a new object of class '<em>Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Property</em>'.
   * @generated
   */
  Property createProperty();

  /**
   * Returns a new object of class '<em>Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute</em>'.
   * @generated
   */
  Attribute createAttribute();

  /**
   * Returns a new object of class '<em>Attribute Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Ref</em>'.
   * @generated
   */
  AttributeRef createAttributeRef();

  /**
   * Returns a new object of class '<em>Initial Attribute Decision</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial Attribute Decision</em>'.
   * @generated
   */
  InitialAttributeDecision createInitialAttributeDecision();

  /**
   * Returns a new object of class '<em>Init Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Init Attribute</em>'.
   * @generated
   */
  InitAttribute createInitAttribute();

  /**
   * Returns a new object of class '<em>Category</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Category</em>'.
   * @generated
   */
  Category createCategory();

  /**
   * Returns a new object of class '<em>Combined Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Combined Attribute</em>'.
   * @generated
   */
  CombinedAttribute createCombinedAttribute();

  /**
   * Returns a new object of class '<em>Combined Attribute Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Combined Attribute Ref</em>'.
   * @generated
   */
  CombinedAttributeRef createCombinedAttributeRef();

  /**
   * Returns a new object of class '<em>Math Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Math Expression</em>'.
   * @generated
   */
  MathExpression createMathExpression();

  /**
   * Returns a new object of class '<em>Int Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Ref</em>'.
   * @generated
   */
  IntRef createIntRef();

  /**
   * Returns a new object of class '<em>Combination</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Combination</em>'.
   * @generated
   */
  Combination createCombination();

  /**
   * Returns a new object of class '<em>Combination Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Combination Ref</em>'.
   * @generated
   */
  CombinationRef createCombinationRef();

  /**
   * Returns a new object of class '<em>Combination Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Combination Condition</em>'.
   * @generated
   */
  CombinationCondition createCombinationCondition();

  /**
   * Returns a new object of class '<em>Dice</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dice</em>'.
   * @generated
   */
  Dice createDice();

  /**
   * Returns a new object of class '<em>Dice Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dice Ref</em>'.
   * @generated
   */
  DiceRef createDiceRef();

  /**
   * Returns a new object of class '<em>Dice Part</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dice Part</em>'.
   * @generated
   */
  DicePart createDicePart();

  /**
   * Returns a new object of class '<em>Raise</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Raise</em>'.
   * @generated
   */
  Raise createRaise();

  /**
   * Returns a new object of class '<em>Attribute Raise</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Raise</em>'.
   * @generated
   */
  AttributeRaise createAttributeRaise();

  /**
   * Returns a new object of class '<em>Attribute Raise Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Raise Type</em>'.
   * @generated
   */
  AttributeRaiseType createAttributeRaiseType();

  /**
   * Returns a new object of class '<em>Dice Based Raise</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dice Based Raise</em>'.
   * @generated
   */
  DiceBasedRaise createDiceBasedRaise();

  /**
   * Returns a new object of class '<em>Constant Based Raise</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constant Based Raise</em>'.
   * @generated
   */
  ConstantBasedRaise createConstantBasedRaise();

  /**
   * Returns a new object of class '<em>Combination Raise</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Combination Raise</em>'.
   * @generated
   */
  CombinationRaise createCombinationRaise();

  /**
   * Returns a new object of class '<em>Combination Raise Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Combination Raise Type</em>'.
   * @generated
   */
  CombinationRaiseType createCombinationRaiseType();

  /**
   * Returns a new object of class '<em>Add Combination</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Combination</em>'.
   * @generated
   */
  AddCombination createAddCombination();

  /**
   * Returns a new object of class '<em>Delete Combination</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delete Combination</em>'.
   * @generated
   */
  DeleteCombination createDeleteCombination();

  /**
   * Returns a new object of class '<em>Decision Table</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Decision Table</em>'.
   * @generated
   */
  DecisionTable createDecisionTable();

  /**
   * Returns a new object of class '<em>Decision Table Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Decision Table Ref</em>'.
   * @generated
   */
  DecisionTableRef createDecisionTableRef();

  /**
   * Returns a new object of class '<em>Row</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Row</em>'.
   * @generated
   */
  Row createRow();

  /**
   * Returns a new object of class '<em>Row Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Row Ref</em>'.
   * @generated
   */
  RowRef createRowRef();

  /**
   * Returns a new object of class '<em>Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition</em>'.
   * @generated
   */
  Condition createCondition();

  /**
   * Returns a new object of class '<em>Condition Targets</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition Targets</em>'.
   * @generated
   */
  ConditionTargets createConditionTargets();

  /**
   * Returns a new object of class '<em>Consequence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Consequence</em>'.
   * @generated
   */
  Consequence createConsequence();

  /**
   * Returns a new object of class '<em>Addition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Addition</em>'.
   * @generated
   */
  Addition createAddition();

  /**
   * Returns a new object of class '<em>Multiplication</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multiplication</em>'.
   * @generated
   */
  Multiplication createMultiplication();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CreatePackage getCreatePackage();

} //CreateFactory
