/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Decision Table Part</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see de.wilkenk.ba.create.CreatePackage#getDecisionTablePart()
 * @model
 * @generated
 */
public enum DecisionTablePart implements Enumerator
{
  /**
   * The '<em><b>Row</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ROW_VALUE
   * @generated
   * @ordered
   */
  ROW(0, "row", "row"),

  /**
   * The '<em><b>Number Condition Rows</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NUMBER_CONDITION_ROWS_VALUE
   * @generated
   * @ordered
   */
  NUMBER_CONDITION_ROWS(1, "numberConditionRows", "numberConditionRows"),

  /**
   * The '<em><b>Number Consequence Rows</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NUMBER_CONSEQUENCE_ROWS_VALUE
   * @generated
   * @ordered
   */
  NUMBER_CONSEQUENCE_ROWS(2, "numberConsequenceRows", "numberConsequenceRows"),

  /**
   * The '<em><b>Name</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NAME_VALUE
   * @generated
   * @ordered
   */
  NAME(3, "name", "name"),

  /**
   * The '<em><b>Row Ref</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ROW_REF_VALUE
   * @generated
   * @ordered
   */
  ROW_REF(4, "RowRef", "RowRef");

  /**
   * The '<em><b>Row</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Row</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ROW
   * @model name="row"
   * @generated
   * @ordered
   */
  public static final int ROW_VALUE = 0;

  /**
   * The '<em><b>Number Condition Rows</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Number Condition Rows</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NUMBER_CONDITION_ROWS
   * @model name="numberConditionRows"
   * @generated
   * @ordered
   */
  public static final int NUMBER_CONDITION_ROWS_VALUE = 1;

  /**
   * The '<em><b>Number Consequence Rows</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Number Consequence Rows</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NUMBER_CONSEQUENCE_ROWS
   * @model name="numberConsequenceRows"
   * @generated
   * @ordered
   */
  public static final int NUMBER_CONSEQUENCE_ROWS_VALUE = 2;

  /**
   * The '<em><b>Name</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Name</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NAME
   * @model name="name"
   * @generated
   * @ordered
   */
  public static final int NAME_VALUE = 3;

  /**
   * The '<em><b>Row Ref</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Row Ref</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ROW_REF
   * @model name="RowRef"
   * @generated
   * @ordered
   */
  public static final int ROW_REF_VALUE = 4;

  /**
   * An array of all the '<em><b>Decision Table Part</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final DecisionTablePart[] VALUES_ARRAY =
    new DecisionTablePart[]
    {
      ROW,
      NUMBER_CONDITION_ROWS,
      NUMBER_CONSEQUENCE_ROWS,
      NAME,
      ROW_REF,
    };

  /**
   * A public read-only list of all the '<em><b>Decision Table Part</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<DecisionTablePart> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Decision Table Part</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DecisionTablePart get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      DecisionTablePart result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Decision Table Part</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DecisionTablePart getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      DecisionTablePart result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Decision Table Part</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DecisionTablePart get(int value)
  {
    switch (value)
    {
      case ROW_VALUE: return ROW;
      case NUMBER_CONDITION_ROWS_VALUE: return NUMBER_CONDITION_ROWS;
      case NUMBER_CONSEQUENCE_ROWS_VALUE: return NUMBER_CONSEQUENCE_ROWS;
      case NAME_VALUE: return NAME;
      case ROW_REF_VALUE: return ROW_REF;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private DecisionTablePart(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //DecisionTablePart
