/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decision Table Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.DecisionTableRef#getDecisionTable <em>Decision Table</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.DecisionTableRef#getPart <em>Part</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getDecisionTableRef()
 * @model
 * @generated
 */
public interface DecisionTableRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Decision Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Decision Table</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decision Table</em>' reference.
   * @see #setDecisionTable(DecisionTable)
   * @see de.wilkenk.ba.create.CreatePackage#getDecisionTableRef_DecisionTable()
   * @model
   * @generated
   */
  DecisionTable getDecisionTable();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.DecisionTableRef#getDecisionTable <em>Decision Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decision Table</em>' reference.
   * @see #getDecisionTable()
   * @generated
   */
  void setDecisionTable(DecisionTable value);

  /**
   * Returns the value of the '<em><b>Part</b></em>' attribute.
   * The literals are from the enumeration {@link de.wilkenk.ba.create.DecisionTablePart}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Part</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Part</em>' attribute.
   * @see de.wilkenk.ba.create.DecisionTablePart
   * @see #setPart(DecisionTablePart)
   * @see de.wilkenk.ba.create.CreatePackage#getDecisionTableRef_Part()
   * @model
   * @generated
   */
  DecisionTablePart getPart();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.DecisionTableRef#getPart <em>Part</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Part</em>' attribute.
   * @see de.wilkenk.ba.create.DecisionTablePart
   * @see #getPart()
   * @generated
   */
  void setPart(DecisionTablePart value);

} // DecisionTableRef
