/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete Combination</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.DeleteCombination#getDelete <em>Delete</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getDeleteCombination()
 * @model
 * @generated
 */
public interface DeleteCombination extends CombinationRaiseType
{
  /**
   * Returns the value of the '<em><b>Delete</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Delete</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delete</em>' containment reference.
   * @see #setDelete(Combination)
   * @see de.wilkenk.ba.create.CreatePackage#getDeleteCombination_Delete()
   * @model containment="true"
   * @generated
   */
  Combination getDelete();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.DeleteCombination#getDelete <em>Delete</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delete</em>' containment reference.
   * @see #getDelete()
   * @generated
   */
  void setDelete(Combination value);

} // DeleteCombination
