/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dice Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.DiceRef#getDice <em>Dice</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.DiceRef#getPart <em>Part</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getDiceRef()
 * @model
 * @generated
 */
public interface DiceRef extends MathExpression
{
  /**
   * Returns the value of the '<em><b>Dice</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dice</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dice</em>' reference.
   * @see #setDice(Dice)
   * @see de.wilkenk.ba.create.CreatePackage#getDiceRef_Dice()
   * @model
   * @generated
   */
  Dice getDice();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.DiceRef#getDice <em>Dice</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dice</em>' reference.
   * @see #getDice()
   * @generated
   */
  void setDice(Dice value);

  /**
   * Returns the value of the '<em><b>Part</b></em>' attribute.
   * The literals are from the enumeration {@link de.wilkenk.ba.create.DicePart}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Part</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Part</em>' attribute.
   * @see de.wilkenk.ba.create.DicePart
   * @see #setPart(DicePart)
   * @see de.wilkenk.ba.create.CreatePackage#getDiceRef_Part()
   * @model
   * @generated
   */
  DicePart getPart();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.DiceRef#getPart <em>Part</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Part</em>' attribute.
   * @see de.wilkenk.ba.create.DicePart
   * @see #getPart()
   * @generated
   */
  void setPart(DicePart value);

} // DiceRef
