/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dice Based Raise</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.DiceBasedRaise#getDiceToUse <em>Dice To Use</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.DiceBasedRaise#getResult <em>Result</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getDiceBasedRaise()
 * @model
 * @generated
 */
public interface DiceBasedRaise extends AttributeRaiseType
{
  /**
   * Returns the value of the '<em><b>Dice To Use</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dice To Use</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dice To Use</em>' reference.
   * @see #setDiceToUse(Dice)
   * @see de.wilkenk.ba.create.CreatePackage#getDiceBasedRaise_DiceToUse()
   * @model
   * @generated
   */
  Dice getDiceToUse();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.DiceBasedRaise#getDiceToUse <em>Dice To Use</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dice To Use</em>' reference.
   * @see #getDiceToUse()
   * @generated
   */
  void setDiceToUse(Dice value);

  /**
   * Returns the value of the '<em><b>Result</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Result</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Result</em>' containment reference.
   * @see #setResult(DiceRef)
   * @see de.wilkenk.ba.create.CreatePackage#getDiceBasedRaise_Result()
   * @model containment="true"
   * @generated
   */
  DiceRef getResult();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.DiceBasedRaise#getResult <em>Result</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Result</em>' containment reference.
   * @see #getResult()
   * @generated
   */
  void setResult(DiceRef value);

} // DiceBasedRaise
