/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dice</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.Dice#getMaxValue <em>Max Value</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getDice()
 * @model
 * @generated
 */
public interface Dice extends Entity
{
  /**
   * Returns the value of the '<em><b>Max Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Max Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Value</em>' attribute.
   * @see #setMaxValue(int)
   * @see de.wilkenk.ba.create.CreatePackage#getDice_MaxValue()
   * @model
   * @generated
   */
  int getMaxValue();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.Dice#getMaxValue <em>Max Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Value</em>' attribute.
   * @see #getMaxValue()
   * @generated
   */
  void setMaxValue(int value);

} // Dice
