/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Math Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.wilkenk.ba.create.CreatePackage#getMathExpression()
 * @model
 * @generated
 */
public interface MathExpression extends EObject
{
} // MathExpression
