/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.Property#getAttrValue <em>Attr Value</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.Property#getCombAttrValue <em>Comb Attr Value</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.Property#getCombValue <em>Comb Value</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends EObject
{
  /**
   * Returns the value of the '<em><b>Attr Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attr Value</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attr Value</em>' reference.
   * @see #setAttrValue(Attribute)
   * @see de.wilkenk.ba.create.CreatePackage#getProperty_AttrValue()
   * @model
   * @generated
   */
  Attribute getAttrValue();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.Property#getAttrValue <em>Attr Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attr Value</em>' reference.
   * @see #getAttrValue()
   * @generated
   */
  void setAttrValue(Attribute value);

  /**
   * Returns the value of the '<em><b>Comb Attr Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comb Attr Value</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comb Attr Value</em>' reference.
   * @see #setCombAttrValue(CombinedAttribute)
   * @see de.wilkenk.ba.create.CreatePackage#getProperty_CombAttrValue()
   * @model
   * @generated
   */
  CombinedAttribute getCombAttrValue();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.Property#getCombAttrValue <em>Comb Attr Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comb Attr Value</em>' reference.
   * @see #getCombAttrValue()
   * @generated
   */
  void setCombAttrValue(CombinedAttribute value);

  /**
   * Returns the value of the '<em><b>Comb Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comb Value</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comb Value</em>' reference.
   * @see #setCombValue(Combination)
   * @see de.wilkenk.ba.create.CreatePackage#getProperty_CombValue()
   * @model
   * @generated
   */
  Combination getCombValue();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.Property#getCombValue <em>Comb Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comb Value</em>' reference.
   * @see #getCombValue()
   * @generated
   */
  void setCombValue(Combination value);

} // Property
