/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Row</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.Row#getIndex <em>Index</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.Row#getConditions <em>Conditions</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.Row#getConsequences <em>Consequences</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getRow()
 * @model
 * @generated
 */
public interface Row extends EObject
{
  /**
   * Returns the value of the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Index</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' attribute.
   * @see #setIndex(int)
   * @see de.wilkenk.ba.create.CreatePackage#getRow_Index()
   * @model
   * @generated
   */
  int getIndex();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.Row#getIndex <em>Index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index</em>' attribute.
   * @see #getIndex()
   * @generated
   */
  void setIndex(int value);

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference list.
   * The list contents are of type {@link de.wilkenk.ba.create.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference list.
   * @see de.wilkenk.ba.create.CreatePackage#getRow_Conditions()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditions();

  /**
   * Returns the value of the '<em><b>Consequences</b></em>' containment reference list.
   * The list contents are of type {@link de.wilkenk.ba.create.Consequence}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Consequences</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consequences</em>' containment reference list.
   * @see de.wilkenk.ba.create.CreatePackage#getRow_Consequences()
   * @model containment="true"
   * @generated
   */
  EList<Consequence> getConsequences();

} // Row
