/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Row Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.RowRef#getRow <em>Row</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.RowRef#getPart <em>Part</em>}</li>
 * </ul>
 *
 * @see de.wilkenk.ba.create.CreatePackage#getRowRef()
 * @model
 * @generated
 */
public interface RowRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Row</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Row</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row</em>' reference.
   * @see #setRow(Row)
   * @see de.wilkenk.ba.create.CreatePackage#getRowRef_Row()
   * @model
   * @generated
   */
  Row getRow();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.RowRef#getRow <em>Row</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Row</em>' reference.
   * @see #getRow()
   * @generated
   */
  void setRow(Row value);

  /**
   * Returns the value of the '<em><b>Part</b></em>' attribute.
   * The literals are from the enumeration {@link de.wilkenk.ba.create.RowPart}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Part</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Part</em>' attribute.
   * @see de.wilkenk.ba.create.RowPart
   * @see #setPart(RowPart)
   * @see de.wilkenk.ba.create.CreatePackage#getRowRef_Part()
   * @model
   * @generated
   */
  RowPart getPart();

  /**
   * Sets the value of the '{@link de.wilkenk.ba.create.RowRef#getPart <em>Part</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Part</em>' attribute.
   * @see de.wilkenk.ba.create.RowPart
   * @see #getPart()
   * @generated
   */
  void setPart(RowPart value);

} // RowRef
