/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create.impl;

import de.wilkenk.ba.create.AttributeRaiseType;
import de.wilkenk.ba.create.CreatePackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute Raise Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AttributeRaiseTypeImpl extends MinimalEObjectImpl.Container implements AttributeRaiseType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeRaiseTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CreatePackage.Literals.ATTRIBUTE_RAISE_TYPE;
  }

} //AttributeRaiseTypeImpl
