/**
 * generated by Xtext 2.10.0
 */
package de.wilkenk.ba.create.impl;

import de.wilkenk.ba.create.CombinedAttribute;
import de.wilkenk.ba.create.CombinedAttributePart;
import de.wilkenk.ba.create.CombinedAttributeRef;
import de.wilkenk.ba.create.CreatePackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Combined Attribute Ref</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.wilkenk.ba.create.impl.CombinedAttributeRefImpl#getCombinedAttribute <em>Combined Attribute</em>}</li>
 *   <li>{@link de.wilkenk.ba.create.impl.CombinedAttributeRefImpl#getPart <em>Part</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CombinedAttributeRefImpl extends ConditionTargetsImpl implements CombinedAttributeRef
{
  /**
   * The cached value of the '{@link #getCombinedAttribute() <em>Combined Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCombinedAttribute()
   * @generated
   * @ordered
   */
  protected CombinedAttribute combinedAttribute;

  /**
   * The default value of the '{@link #getPart() <em>Part</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPart()
   * @generated
   * @ordered
   */
  protected static final CombinedAttributePart PART_EDEFAULT = CombinedAttributePart.COMB_ATTR_NAME;

  /**
   * The cached value of the '{@link #getPart() <em>Part</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPart()
   * @generated
   * @ordered
   */
  protected CombinedAttributePart part = PART_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CombinedAttributeRefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CreatePackage.Literals.COMBINED_ATTRIBUTE_REF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CombinedAttribute getCombinedAttribute()
  {
    if (combinedAttribute != null && combinedAttribute.eIsProxy())
    {
      InternalEObject oldCombinedAttribute = (InternalEObject)combinedAttribute;
      combinedAttribute = (CombinedAttribute)eResolveProxy(oldCombinedAttribute);
      if (combinedAttribute != oldCombinedAttribute)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, CreatePackage.COMBINED_ATTRIBUTE_REF__COMBINED_ATTRIBUTE, oldCombinedAttribute, combinedAttribute));
      }
    }
    return combinedAttribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CombinedAttribute basicGetCombinedAttribute()
  {
    return combinedAttribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCombinedAttribute(CombinedAttribute newCombinedAttribute)
  {
    CombinedAttribute oldCombinedAttribute = combinedAttribute;
    combinedAttribute = newCombinedAttribute;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CreatePackage.COMBINED_ATTRIBUTE_REF__COMBINED_ATTRIBUTE, oldCombinedAttribute, combinedAttribute));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CombinedAttributePart getPart()
  {
    return part;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPart(CombinedAttributePart newPart)
  {
    CombinedAttributePart oldPart = part;
    part = newPart == null ? PART_EDEFAULT : newPart;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CreatePackage.COMBINED_ATTRIBUTE_REF__PART, oldPart, part));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CreatePackage.COMBINED_ATTRIBUTE_REF__COMBINED_ATTRIBUTE:
        if (resolve) return getCombinedAttribute();
        return basicGetCombinedAttribute();
      case CreatePackage.COMBINED_ATTRIBUTE_REF__PART:
        return getPart();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CreatePackage.COMBINED_ATTRIBUTE_REF__COMBINED_ATTRIBUTE:
        setCombinedAttribute((CombinedAttribute)newValue);
        return;
      case CreatePackage.COMBINED_ATTRIBUTE_REF__PART:
        setPart((CombinedAttributePart)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CreatePackage.COMBINED_ATTRIBUTE_REF__COMBINED_ATTRIBUTE:
        setCombinedAttribute((CombinedAttribute)null);
        return;
      case CreatePackage.COMBINED_ATTRIBUTE_REF__PART:
        setPart(PART_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CreatePackage.COMBINED_ATTRIBUTE_REF__COMBINED_ATTRIBUTE:
        return combinedAttribute != null;
      case CreatePackage.COMBINED_ATTRIBUTE_REF__PART:
        return part != PART_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (part: ");
    result.append(part);
    result.append(')');
    return result.toString();
  }

} //CombinedAttributeRefImpl
